apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bot-chart.fullname" . }}-secret
  labels:
  {{- include "bot-chart.labels" . | nindent 4 }}
type: Opaque
data:
  access: {{ .Values.botServer.access | b64enc }}
  droneToken: {{ .Values.botServer.droneToken | b64enc}}
  webhookToken: {{ .Values.botServer.webhookToken | b64enc}}
  adminAccess: {{.Values.botServer.adminAccess| b64enc}}
