apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bot-chart.fullname" . }}-config
  labels:
  {{- include "bot-chart.labels" . | nindent 4 }}
data:
  hookUrl: http://{{.Values.botServer.hookUrl}}
  baseUrl: {{.Values.botServer.baseUrl}}
  botUser: {{.Values.botServer.botUser}}

